**Question 1:** 
What is the value of Z after the following code is run:

In [ ]:
X=np.array([[1,0],[0,1]])
Y=np.array([[0,1],[1,0]])
Z=X+Y

array([[1, 1],[1, 1]])

**Question 2:**
What values does the variable out take if the following lines of code are run:

In [ ]:
X=np.array([[1,0,1],[2,2,2]]) 
out=X[0:2,2]
out

array([1, 2])

**Question 3:**
What is the value of Z after the following code is run:

In [ ]:
X=np.array([[1,0],[0,1]])
Y=np.array([[2,1],[1,2]]) 
Z=np.dot(X,Y)

array([[2, 1],[1, 2]])